spring:
  datasource:
    url: jdbc:mysql://localhost:3307/catalog_db
    username: catalog_user
    password: catalog_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutos

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: Catalog Service API
    description: Servicio de catálogo maestro con MySQL (categorías, tags, imágenes)
    version: 1.0.0
    contact:
      name: TecyLab Team
      email: renato.garay@pucp.pe

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tecylab.catalog: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"